version: "3"
name: "cyberpecker-api"

services:
    redis:
        image: redis
        container_name: redis
        restart: always
        networks:
            - cyberpecker-api
        ports:
            - "6379:6379"

    api:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: api
        restart: always
        networks:
            - cyberpecker-api
        env_file:
            - ./.env
        environment:
            - DATABASE_ADDRESS=redis:6379
            - DATABASE_PASSWORD=
        ports:
            - "8000:8000"
        depends_on:
            - redis

networks:
    cyberpecker-api:
        name: cyberpecker-api
